package subtitles

import (
	"strings"
	"testing"
	"time"

	"github.com/devosurf/cuescribe/internal/transcript"
)

func TestParseVTTPreservesVoiceSpeaker(t *testing.T) {
	input := `WEBVTT

NOTE generated by fixture

00:00:01.000 --> 00:00:03.500
<v Alice>Hello &amp; welcome</v>
`
	segments, err := ParseVTT(strings.NewReader(input))
	if err != nil {
		t.Fatalf("ParseVTT() error = %v", err)
	}
	if len(segments) != 1 {
		t.Fatalf("len(segments) = %d, want 1", len(segments))
	}
	if segments[0].Start != time.Second || segments[0].End != 3500*time.Millisecond {
		t.Fatalf("timestamps = %v..%v", segments[0].Start, segments[0].End)
	}
	if segments[0].Speaker != "Alice" {
		t.Fatalf("speaker = %q, want Alice", segments[0].Speaker)
	}
	if segments[0].Text != "Hello & welcome" {
		t.Fatalf("text = %q", segments[0].Text)
	}
}

func TestParseVTTCollapsesYouTubeRollingCaptions(t *testing.T) {
	input := `WEBVTT

00:11:49.000 --> 00:11:51.000
Exact same thing Google just did with

00:11:49.500 --> 00:11:52.000
Exact same thing Google just did with their home automations. Just describe

00:11:51.000 --> 00:11:53.000
their home automations. Just describe

00:11:51.500 --> 00:11:54.000
their home automations. Just describe the automation, it'll build it, then you

00:11:53.000 --> 00:11:55.000
the automation, it'll build it, then you
`
	segments, err := ParseVTT(strings.NewReader(input))
	if err != nil {
		t.Fatalf("ParseVTT() error = %v", err)
	}
	got := segmentTexts(segments)
	want := []string{
		"Exact same thing Google just did with",
		"their home automations. Just describe",
		"the automation, it'll build it, then you",
	}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Fatalf("texts = %#v, want %#v", got, want)
	}
}

func TestParseVTTLeavesOrdinaryAdjacentCaptionsAlone(t *testing.T) {
	input := `WEBVTT

00:00:01.000 --> 00:00:02.000
Hello there

00:00:02.000 --> 00:00:03.000
There is more to say

00:00:03.000 --> 00:00:04.000
More work follows
`
	segments, err := ParseVTT(strings.NewReader(input))
	if err != nil {
		t.Fatalf("ParseVTT() error = %v", err)
	}
	got := segmentTexts(segments)
	want := []string{"Hello there", "There is more to say", "More work follows"}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Fatalf("texts = %#v, want %#v", got, want)
	}
}

func TestParseSRTPreservesSpeakerLabel(t *testing.T) {
	input := `1
00:00:01,000 --> 00:00:02,000
Speaker 1: Hello there
`
	segments, err := ParseSRT(strings.NewReader(input))
	if err != nil {
		t.Fatalf("ParseSRT() error = %v", err)
	}
	if len(segments) != 1 {
		t.Fatalf("len(segments) = %d, want 1", len(segments))
	}
	if segments[0].Speaker != "Speaker 1" {
		t.Fatalf("speaker = %q", segments[0].Speaker)
	}
	if segments[0].Text != "Hello there" {
		t.Fatalf("text = %q", segments[0].Text)
	}
}

func segmentTexts(segments []transcript.Segment) []string {
	texts := make([]string, 0, len(segments))
	for _, segment := range segments {
		texts = append(texts, segment.Text)
	}
	return texts
}
