package subtitles

import (
	"strings"
	"testing"
	"time"
)

func TestParseVTTPreservesVoiceSpeaker(t *testing.T) {
	input := `WEBVTT

NOTE generated by fixture

00:00:01.000 --> 00:00:03.500
<v Alice>Hello &amp; welcome</v>
`
	segments, err := ParseVTT(strings.NewReader(input))
	if err != nil {
		t.Fatalf("ParseVTT() error = %v", err)
	}
	if len(segments) != 1 {
		t.Fatalf("len(segments) = %d, want 1", len(segments))
	}
	if segments[0].Start != time.Second || segments[0].End != 3500*time.Millisecond {
		t.Fatalf("timestamps = %v..%v", segments[0].Start, segments[0].End)
	}
	if segments[0].Speaker != "Alice" {
		t.Fatalf("speaker = %q, want Alice", segments[0].Speaker)
	}
	if segments[0].Text != "Hello & welcome" {
		t.Fatalf("text = %q", segments[0].Text)
	}
}

func TestParseSRTPreservesSpeakerLabel(t *testing.T) {
	input := `1
00:00:01,000 --> 00:00:02,000
Speaker 1: Hello there
`
	segments, err := ParseSRT(strings.NewReader(input))
	if err != nil {
		t.Fatalf("ParseSRT() error = %v", err)
	}
	if len(segments) != 1 {
		t.Fatalf("len(segments) = %d, want 1", len(segments))
	}
	if segments[0].Speaker != "Speaker 1" {
		t.Fatalf("speaker = %q", segments[0].Speaker)
	}
	if segments[0].Text != "Hello there" {
		t.Fatalf("text = %q", segments[0].Text)
	}
}
